name: XRCraft
main: club.umdxr.minecraft.Main
version: 1.0
api-version: "1.20"
author: djfigs1
description: "The homemade minecraft plugin of the XR Club at the University of Maryland: College Park!"
commands:
  pvp:
    description: Opt in/out of PvP
  saypos:
    description: Broadcast your coordinates to other players
  afk:
    description: Toggles AFK
  waypoint:
    aliases: wp